"""
Django settings for endoreg_db_api project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from lx_webapp.base_settings import (
    BASE_DIR,
    LANGUAGE_CODE,
    TIME_ZONE,
    USE_I18N,
    USE_TZ,
    DEFAULT_AUTO_FIELD,
    INSTALLED_APPS,
    MIDDLEWARE,
    ROOT_URLCONF,
    TEMPLATES,
    AUTH_PASSWORD_VALIDATORS
)

from dotenv import load_dotenv
load_dotenv('lx-webapp.env')

##### env vars
DEPLOYMENT_MODE = os.getenv('DEPLOYMENT_MODE', None)
SECRET_KEY = os.getenv('SECRET_KEY', None)
STATIC_URL = os.getenv('STATIC_URL', '/static/')
assert DEPLOYMENT_MODE in ["dev", "prod"], f"DEPLOYMENT_MODE ({DEPLOYMENT_MODE}) must be either 'dev' or 'prod'"

if DEPLOYMENT_MODE == "dev":
    from .settings_dev import *
elif DEPLOYMENT_MODE == "prod":
    from .settings_prod import *
#

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Add other static directories if needed
]
# WhiteNoise configuration to automatically compress and cache files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Application definition
WSGI_APPLICATION = 'lx_webapp.wsgi.application'
